### ISSUE TITLE
BUG: Error is thrown with Pandas 1.2.x

### ISSUE THREAD

**Issue by zach401** [zach401/acnportal#90]
-   \[x] I have checked that this issue has not already been reported.
-   \[x] I have confirmed this bug exists on the latest version of acnportal.

**Describe the bug**
acnportal throws an error on import for pandas >1.2

**To Reproduce**
Import acnportal with pandas >1.2 installed.

**Expected behavior**
No error should be thrown.

**Screenshots**
```
======================================================================
246ERROR: acnportal.acnsim (unittest.loader._FailedTest)
247----------------------------------------------------------------------
248ImportError: Failed to import test module: acnportal.acnsim
249Traceback (most recent call last):
250  File "/opt/python/3.7.1/lib/python3.7/unittest/loader.py", line 468, in _find_test_path
251    package = self._get_module_from_name(name)
252  File "/opt/python/3.7.1/lib/python3.7/unittest/loader.py", line 375, in _get_module_from_name
253    __import__(name)
254  File "/home/travis/build/zach401/acnportal/acnportal/acnsim/__init__.py", line 1, in <module>
255    from .simulator import Simulator
256  File "/home/travis/build/zach401/acnportal/acnportal/acnsim/simulator.py", line 11, in <module>
257    from .events import *
258  File "/home/travis/build/zach401/acnportal/acnportal/acnsim/events/__init__.py", line 1, in <module>
259    from .event import Event
260  File "/home/travis/build/zach401/acnportal/acnportal/acnsim/events/event.py", line 7, in <module>
261    from ..base import BaseSimObj
262  File "/home/travis/build/zach401/acnportal/acnportal/acnsim/base.py", line 17, in <module>
263    from pandas.io.common import stringify_path, get_handle, get_filepath_or_buffer
264ImportError: cannot import name 'get_filepath_or_buffer' from 'pandas.io.common' (/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pandas/io/common.py)
```

**Comment by zach401** [comment]
We have temporarily fixed this issue by adding the line:
`"pandas >= 1.1.0, < 1.2.0",`

in setup.py. 

However we should update the code so that it works with pandas >= 1.2.0.

**Comment by chrisyeh96** [comment]
Being able to support newer versions of pandas would be much appreciated!

**Comment by sunash** [comment]
The error arises from the serializer (base.from_json) attempting to use a function in pandas 1.1 that doesn't exist in pandas 1.2. One possible fix would be to look at the get_filepath_or_buffer function's internals and rewrite that function within acnsim for use by the serializer. Or, we could see how the new version of pandas currently reads DataFrames from files and copy that into the serializer. I don't immediately have time to work on this fix, but if anyone wants to take a stab at it, I'd be happy to code review a potential solution.
